export const DEFAULT_PREFIX_DATA = [
  {
    id: 1,
    optionText: "낮은 생명력 상태일 때 즉시 회복",
    filterRegex: "허둥",
    maxRollRegex: "11%.감",
    itemLevel: "81",
    type: "생명력",
  },
  {
    id: 2,
    optionText: "회복량의 50%를 즉시 회복",
    filterRegex: "부글",
    maxRollRegex: "량.36%.감",
    itemLevel: "79",
    type: "생명력, 마나",
  },
  {
    id: 3,
    optionText: "회복량 증가, 회복 속도 감소",
    filterRegex: "포화",
    maxRollRegex: "량.70%.증",
    itemLevel: "81",
    type: "생명력, 마나",
  },
  {
    id: 4,
    optionText: "즉시 회복",
    filterRegex: "끓어",
    maxRollRegex: "끓어",
    itemLevel: "7",
    type: "생명력, 마나",
  },
  {
    id: 5,
    optionText: "치명타 명중 시 플라스크 1 충전",
    filterRegex: "의사",
    maxRollRegex: "시.35%",
    itemLevel: "80",
    type: "생명력, 마나, 특수",
  },
  {
    id: 6,
    optionText: "적에게 피격 시 충전 3 획득",
    filterRegex: "고행",
    maxRollRegex: "고행",
    itemLevel: "80",
    type: "생명력, 마나, 특수",
  },
  {
    id: 7,
    optionText: "충전 소모량 감소",
    filterRegex: "화학",
    maxRollRegex: "모량.28%.감",
    itemLevel: "82",
    type: "생명력, 마나, 특수",
  },
  {
    id: 8,
    optionText: "마나가 찼을 때 효과가 제거되지 않음",
    filterRegex: "인내",
    maxRollRegex: "인내",
    itemLevel: "16",
    type: "마나",
  },
  {
    id: 9,
    optionText: "지속시간 감소, 효과 25% 증가",
    filterRegex: "과.25%.증",
    maxRollRegex: "간.23%.감",
    itemLevel: "80",
    type: "특수",
  },
  {
    id: 10,
    optionText: "지속시간 증가",
    filterRegex: "실험",
    maxRollRegex: "간.40%.증",
    itemLevel: "84",
    type: "특수",
  },
  {
    id: 11,
    optionText: "효과 증가, 마나 연소 속도 증가",
    filterRegex: "첨가",
    maxRollRegex: "도.37%.증",
    itemLevel: "84",
    type: "팅크",
  },
];

export const DEFAULT_SUFFIX_DATA = [
  {
    id: 101,
    optionText: "출혈 · 타락한 피 면역 부여 (조건부)",
    filterRegex: "속풀",
    maxRollRegex: "(17.*출 17.*타)",
    itemLevel: "80",
    type: "생명력, 마나",
  },
  {
    id: 102,
    optionText: "냉각 · 동결 면역 부여 (조건부)",
    filterRegex: "녹이",
    maxRollRegex: "(17.*냉 17.*동)",
    itemLevel: "76",
    type: "생명력, 마나",
  },
  {
    id: 103,
    optionText: "방어도 증가",
    filterRegex: "딜로",
    maxRollRegex: "어도.60",
    itemLevel: "84",
    type: "특수",
  },
  {
    id: 104,
    optionText: "회피 증가",
    filterRegex: "임팔",
    maxRollRegex: "회피.60",
    itemLevel: "84",
    type: "특수",
  },
  {
    id: 105,
    optionText: "이동 속도 증가",
    filterRegex: "치타",
    maxRollRegex: "속도.14",
    itemLevel: "85",
    type: "특수",
  },
  {
    id: 106,
    optionText: "추가 원소 저항",
    filterRegex: "무지",
    maxRollRegex: "저항.20",
    itemLevel: "81",
    type: "특수",
  },
  {
    id: 107,
    optionText: "치명타 확률 증가",
    filterRegex: "절개",
    maxRollRegex: "률.55",
    itemLevel: "82",
    type: "특수",
  },
  {
    id: 108,
    optionText: "기절 긴급회피",
    filterRegex: "끈기",
    maxRollRegex: "55.*기절",
    itemLevel: "80",
    type: "특수",
  },
  {
    id: 109,
    optionText: "저주 효과 감소",
    filterRegex: "올빼",
    maxRollRegex: "저주.*65",
    itemLevel: "84",
    type: "특수",
  },
  {
    id: 110,
    optionText: "감전 긴급회피",
    filterRegex: "습지",
    maxRollRegex: "감전.*55",
    itemLevel: "82",
    type: "특수",
  },
  {
    id: 111,
    optionText: "원소 저항 관통",
    filterRegex: "압도$",
    maxRollRegex: "19%.관",
    itemLevel: "85",
    type: "팅크",
  },
  {
    id: 112,
    optionText: "치명타 피해 배율",
    filterRegex: "흉포",
    maxRollRegex: "배율.*33",
    itemLevel: "85",
    type: "팅크",
  },
  {
    id: 113,
    optionText: "공격 속도 증가",
    filterRegex: "숙련",
    maxRollRegex: "속도.29",
    itemLevel: "85",
    type: "팅크",
  },
];
